### PR TITLE
Feat: Initial commit for the accordion.

### PR DESCRIPTION
**Pull request by code-mattclaffey**
Hey guys,

Wrote an accordion component. Please give feedback on the JS and readme. 

Thank you

### CODE REVIEW

**Comment by furzeface** [comment]
Only thing I can see is removing `aria-selected` from the all accordion handles except for the current one, when another is selected.

**Comment by tawashley** [comment]
More of a behaviour question, however, should you also have `aria-hidden` on all BUT selected accordion item as well?

**Comment by code-mattclaffey** [comment]
@tawashley do you mean aria-hidden should be on the `li` element?

**Comment by code-mattclaffey** [comment]
@furzeface @tawashley 

I have had a re look at the accordion and made a V2/refactor of the component. 

Things I have done:

- Show all tabs open on no-js
- have the option to keep tabs open or not
- add aria-hidden when javascript is enabled
- refactored a lot of repetitive code.

**Comment by tawashley** [comment]
Is it fair to assume the behaviour of removing the `no-js` would be done outside of the component behaviour? Somewhere like `App.js`? Does it need to be as part of the accordion?

**Comment by code-mattclaffey** [comment]
@tawashley makes sense. I can get rid of it.

**Comment by tawashley** [comment]
@code-mattclaffey Aces! 👍

**Comment by furzeface** [comment]
I'd be tempted to go ahead and use CSS `:target` to show/hide the accordion content with JS disabled. I'm happy to add this in for a next iteration. Let's merge this now.

**Pull request merged**
